name: Push into Main
on:
  push:
    branches: main

jobs:
  test:
    runs-on: runner-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Dir
        run: ls -lah
        
      - name: Tests
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: docker-compose.yml
