name: Build Image in Main
on:
  push:
    branches: main
env:
  DOCKER_IMAGE: canvas-tetris-afriansyah

jobs:
  Canvas_Image:
    runs-on: runner-sgdo
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Check Dir
        run: ls -lah canvas-tetris/tetris

      - name: build-image
        run: docker build -t $DOCKER_IMAGE:1.0 canvas-tetris/tetris/.

      - name: Deploy Tetris
        run: |
          docker-compose -f canvas-tetris/tetris/docker-compose.yml down --rmi all
          docker-compose -f canvas-tetris/tetris/docker-compose.yml up -d

    