name: Push into Main
on:
  push:
    branches: main

jobs:
  BuildAndRunImageviaCompose:
    runs-on: runner-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Dir
        run: |
          ls -lah
        
      - name: Compose Down
        run: docker-compose -f apps/docker-compose.yml down --rmi all
        
      - name: Compose Build
        run: |
          docker-compose -f apps/docker-compose.yml up -d --build
          docker ps -a
          curl localhost:8070

      - name: Compose Down Again
        run: docker-compose down --rmi all
